spring:
  application:
    name: hello
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create   #update
    properties:
      hibernate:
        format_sql: true
  thymeleaf:
    prefix: classpath:/templates/   #???
    suffix: .html    #???

logging:
  level:
    org.hibernate.SQL: debug  #??? sql? ??? ??? ????.
    org.hibernate.orm.jdbc.bind: trace